### ISSUE TITLE
Herald.settings.queueTimer doesn't seem to work?

### ISSUE THREAD

**Issue by SachaG** [Meteor-Reaction/Herald#49]
I have this code to shorten the delay when sending emails in my dev environment, but it doesn't seem to do anything?

```js
  // send emails every second when in dev environment
  if (Meteor.absoluteUrl().indexOf('localhost') !== -1)
    Herald.settings.queueTimer = 1000;
```

**Comment by Kestanous** [comment]
Are you running that before or after meteor startup? See https://github.com/Meteor-Reaction/Herald/blob/master/server/escalate.js#L5. Once started it, currently, does not restart the interval. That may need to change depending on your needs.

**Comment by SachaG** [comment]
Oh, that makes sense. I was running it after startup. 

By the way, sorry if this is a dumb question but what are the advantages of delaying and grouping the calls like this?

**Comment by Kestanous** [comment]
Ah yep, that will do it.

So there is actually no true advantage right now. In theory it would make sure the server only does one at a time and would not be overloaded by Herald, but node already does a good job with that anyway. 

The real reason I added it was to allow devs to "time" notifications. For example lets say you have set up mobile push with sound, not available with herald yet. Lets also assume this is an international service like Github and notifications could be triggered at any time of day. In theory you do do things like don't send the user notifications between 20:00-8:00(10PM-8AM) user time, because they may be asleep or have requested silence in that range. So at 8:00(AM) you send off all the users notifications or, also not implemented, aggregate them all together into a "Here's what you missed!".

**Comment by SachaG** [comment]
OK, makes sense. And I guess you could also do stuff like cancel the email
notification if the web notification is marked as read.

**Comment by Kestanous** [comment]
Ah yes, I forgot about that. I think that actually is already in play. 

Closing this, unless there was something else? 

I may find a better way to use/remove the queue in Herald v2 but for now it works well enough. I just wish it would not squash errors, makes debugging a total pain.
